<body>
    <?php
    include("../elements/nav.php");
    ?>

    <main>

        <!-- This text is generated by AI based on the fictitious company name "Cybernetics innovations.
    I am aware of the rules about the use of AI for these assignments. Almost all of what I have coded
    is self-written and some parts of the css have been either copied from stackoverflow.com or learned from https://www.w3schools.com.
    I must say that the name of the company was still my idea and my reason for using AI to generate the background was for filling in any illogical plotholes
    I may have accidentally left in including any inconsistancies-->

        <div id="about">
            <h2>Over Ons</h2>
            <section>
                <h3>Who We Are</h3>

                <p>
                    Cybernetics Innovations is a forward-thinking technology
                    company focused on building modern digital solutions for
                    businesses and organizations. Our goal is to combine creativity,
                    engineering, and innovation to create systems that improve efficiency
                    and help companies grow in an increasingly digital world.

                    Our team specializes in developing advanced technological solutions
                    ranging from software development and automation to digital platforms
                    that connect people and ideas. At Cybernetics Innovations,
                    we believe that technology should not only solve problems but
                    also open the door to new possibilities.
                </p>
            </section>

            <br>
            <section>
                <h3>Our Mission</h3>
                <p>
                    At Cybernetics Innovations, our mission is to design
                    reliable, innovative, and future-proof technology that
                    helps businesses stay ahead in a rapidly evolving digital
                    landscape. We focus on delivering high-quality solutions
                    that are both practical and scalable.

                    We are committed to continuous learning and innovation,
                    ensuring that our services adapt to the latest technological
                    developments. By working closely with our clients, we aim to
                    create solutions that are tailored to their needs and capable
                    of supporting long-term success.
                </p>
            </section>
        </div>




    </main>

    <?php
    include("../elements/footer.php");
    ?>
</body>